# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LXQVWZTFaW1bOQu7gkBS0aQ5nulduTS
"""

menu = """

[d] Depositar
[s] Sacar
[e] Extrato
[q] Sair

=> """

saldo_corrente = 0
saldo_poupanca = 0
limite = 500
extrato_corrente = ""
extrato_poupanca = ""
numero_saques_corrente = 0
numero_saques_poupanca = 0
LIMITE_SAQUES = 3

def escolher_conta():
    print("\nEscolha a conta:")
    print("[1] Conta Corrente")
    print("[2] Conta Poupança")
    return input("=> ")

while True:

    opcao = input(menu)

    if opcao == "d":
        tipo_conta = escolher_conta()
        valor = float(input("Informe o valor do depósito: "))

        if valor > 0:
            if tipo_conta == "1":
                saldo_corrente += valor
                extrato_corrente += f"Depósito: R$ {valor:.2f}\n"
            elif tipo_conta == "2":
                saldo_poupanca += valor
                extrato_poupanca += f"Depósito: R$ {valor:.2f}\n"
            else:
                print("Conta inválida.")
        else:
            print("Operação falhou! O valor informado é inválido.")

    elif opcao == "s":
        tipo_conta = escolher_conta()
        valor = float(input("Informe o valor do saque: "))

        if tipo_conta == "1":
            saldo = saldo_corrente
            extrato = extrato_corrente
            numero_saques = numero_saques_corrente
        elif tipo_conta == "2":
            saldo = saldo_poupanca
            extrato = extrato_poupanca
            numero_saques = numero_saques_poupanca
        else:
            print("Conta inválida.")
            continue

        excedeu_saldo = valor > saldo
        excedeu_limite = valor > limite
        excedeu_saques = numero_saques >= LIMITE_SAQUES

        if excedeu_saldo:
            print("Operação falhou! Você não tem saldo suficiente.")
        elif excedeu_limite:
            print("Operação falhou! O valor do saque excede o limite.")
        elif excedeu_saques:
            print("Operação falhou! Número máximo de saques excedido.")
        elif valor > 0:
            if tipo_conta == "1":
                saldo_corrente -= valor
                extrato_corrente += f"Saque: R$ {valor:.2f}\n"
                numero_saques_corrente += 1
            elif tipo_conta == "2":
                saldo_poupanca -= valor
                extrato_poupanca += f"Saque: R$ {valor:.2f}\n"
                numero_saques_poupanca += 1
        else:
            print("Operação falhou! O valor informado é inválido.")

    elif opcao == "e":
        tipo_conta = escolher_conta()

        if tipo_conta == "1":
            print("\n================ EXTRATO CONTA CORRENTE ================")
            print("Não foram realizadas movimentações." if not extrato_corrente else extrato_corrente)
            print(f"\nSaldo: R$ {saldo_corrente:.2f}")
        elif tipo_conta == "2":
            print("\n================ EXTRATO CONTA POUPANÇA ================")
            print("Não foram realizadas movimentações." if not extrato_poupanca else extrato_poupanca)
            print(f"\nSaldo: R$ {saldo_poupanca:.2f}")
        else:
            print("Conta inválida.")
        print("========================================================")

    elif opcao == "q":
        break

    else:
        print("Operação inválida, por favor selecione novamente a operação desejada.")